<a href="https://colab.research.google.com/github/p4arth/PyttorchLearning/blob/main/PytorchAutograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
x = torch.randn(3, requires_grad=True) # Creates computational graph
print(x) 

tensor([-0.5171, -1.9311, -0.9759], requires_grad=True)


In [12]:
y = x+2
print(y)
z = y*y*2
print(z)
# z = z.mean() 
print(z)

tensor([1.4829, 0.0689, 1.0241], grad_fn=<AddBackward0>)
tensor([4.3980, 0.0095, 2.0975], grad_fn=<MulBackward0>)
tensor([4.3980, 0.0095, 2.0975], grad_fn=<MulBackward0>)


In [14]:
x.requires_grad_(False)

tensor([-0.5171, -1.9311, -0.9759])

In [15]:
with torch.no_grad():
   y = x + 2
print(y)

tensor([1.4829, 0.0689, 1.0241])


In [20]:
weights = torch.ones(4, requires_grad=True)
print(weights)
for epoch in range(4):
  model_output = (weights*3).sum()  # doing backprop
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
